# Install Numpy

```
pip install numpy

```

# Import Numpy

```
import numpy as np
```

# Coding

In [6]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [9]:
b = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# np.zeros() & np.ones()

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.empty(2)

array([-2.91808470e+115,  1.55290738e+156])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(5, 30, 5)

array([ 5, 10, 15, 20, 25])

In [19]:
np.linspace(0,10, num=3)

array([ 0.,  5., 10.])

In [22]:
np.ones(2, dtype=np.int64)

array([1, 1], dtype=int64)

In [23]:
np.array(a)

array([1, 2, 3, 4, 5])

In [27]:
x = np.array([3, 1, 2]);
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [29]:
sr1 = np.array([1,2,3,4])
sr2 = np.array([5,6,7,8])
np.concatenate((sr1,sr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
sr1.ndim

1

In [33]:
sr1.size

4

In [34]:
sr1.shape

(4,)

In [36]:
arr = np.arange(20).reshape((4,5))

In [40]:
mask = arr > 2;
print(arr[mask])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [41]:
print(np.__version__)

1.21.5


In [44]:
temp_arr = np.array([22,12,23,87,16])
temp_arr1 = temp_arr.copy()
temp_arr1[0] = 55
print(temp_arr1)
print(temp_arr)

[55 12 23 87 16]
[22 12 23 87 16]


In [49]:
np.random.rand()

0.7448074457515506

In [51]:
np.random.randint(100, size=(3, 5))

array([[50,  1, 90,  3, 54],
       [30, 72, 66, 45, 66],
       [86, 71, 51, 37, 20]])

In [53]:
x_random = np.random.choice([3, 5, 7, 9], size=(3, 5))
print(x_random)

[[7 9 7 7 5]
 [9 7 3 5 7]
 [9 3 3 9 3]]
