In [1]:
import numpy as np

In [13]:
data = np.loadtxt("../../datasets/fitness.txt", dtype="str")
data

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '10

In [17]:
date,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg = data.T

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [3]:
n_array = np.array([0,1,0,2,0,0,3,0,5,7,0,0,8])
res = np.where(n_array == 0)[0]
res

array([ 0,  2,  4,  5,  7, 10, 11], dtype=int64)

In [4]:
arr = [[1,4,5],[2,0,1],[4,4,2]]
arr

[[1, 4, 5], [2, 0, 1], [4, 4, 2]]

In [5]:
sum(np.diag(arr))

3

In [6]:
sum(np.where(np.diagonal=True))

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (3319986504.py, line 1)

In [7]:
np.diagonal(arr).sum()

3

In [8]:
sum(np.diagonal(arr))

3

In [9]:
arr1 = np.array([10,52,62,16,16,54,453])
arr1

array([ 10,  52,  62,  16,  16,  54, 453])

In [10]:
np.argsort(arr1)

array([0, 3, 4, 1, 5, 2, 6], dtype=int64)