In [2]:
import numpy as np

In [2]:
a = np.arange(1,11);
def complicated(s):
    return np.exp(s);

func1 = np.vectorize(complicated)
func1(a)


array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [3]:
a= np.arange(4)

In [4]:
d=a*1
d[0]=100
d

array([100,   1,   2,   3])

In [5]:
a

array([0, 1, 2, 3])

In [6]:
a = np.arange(1,25).reshape(2, 3, 4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [7]:
a[:,:,::2]

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11]],

       [[13, 15],
        [17, 19],
        [21, 23]]])

# Splitting

In [8]:
d = np.arange(1, 13)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
np.split(d, 4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [3]:
arr1 = np.array([1,2,3,6,3,2]) 

arr2 = np.array([4,2,1,3,3,2]) 

arr3 = np.zeros(len(arr1)) 

In [5]:
for i in range(len(arr1)): 

    arr3[i] = arr1[i] * arr2[i] 

In [7]:
arr3 = arr1*arr2 
arr3

array([ 4,  4,  3, 18,  9,  4])

In [8]:
for i in range(len(arr1)): 

    if(arr1[i] < 0 ): 

        arr1[i] = -1 

    else: 

        arr1[i] = 1

In [9]:
arr1

array([1, 1, 1, 1, 1, 1])

In [10]:
np.where(arr1 > 0, 1, -1) 

array([1, 1, 1, 1, 1, 1])

In [13]:
xyz = np.array([[[0, 1], 
             [2, 3]], 
 
            [[4, 5], 
             [6, 7]]])
xyz

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
xyz[:, 0:, :1]

array([[[0],
        [2]],

       [[4],
        [6]]])

# Deep Copy

In [15]:
arr = np.array([1,2,3,0,-2,4])

In [17]:
arr1 = arr*1
arr
arr1

array([ 1,  2,  3,  0, -2,  4])

In [21]:
arr1 = arr[:]
arr
arr1

array([ 1,  2,  3,  0, -2,  4])

In [22]:
arr1 = arr[arr > 0]
arr
arr1

array([1, 2, 3, 4])

In [30]:
arr1 = arr.reshape(2,3)
arr1

array([[ 1,  2,  3],
       [ 0, -2,  4]])

# Concatenate

In [25]:
d = np.arange(1,5)
e = np.arange(2, 6)
print(d)
print(e)

[1 2 3 4]
[2 3 4 5]


In [26]:
np.concatenate([d,e])

array([1, 2, 3, 4, 2, 3, 4, 5])

In [29]:
np.concatenate([d,e], axis=0)

array([1, 2, 3, 4, 2, 3, 4, 5])

In [46]:
d = np.arange(1,13).reshape(3,4)
e = np.arange(1,5)
print(d)
print(e)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


In [49]:
# error
np.concatenate([d,e.T], axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# hstack() & vstack()

In [50]:
d = np.arange(1,5)
e = np.arange(2,6)
print(d)
print(e)

[1 2 3 4]
[2 3 4 5]


In [55]:
np.vstack([d,e])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [56]:
np.hstack([d,e])

array([1, 2, 3, 4, 2, 3, 4, 5])

In [59]:
d = np.arange(1,5).reshape(2,2)
e = np.arange(2,6).reshape(2,2)
print(d)
print(e)

[[1 2]
 [3 4]]
[[2 3]
 [4 5]]


In [60]:
np.hstack([d,e])

array([[1, 2, 2, 3],
       [3, 4, 4, 5]])

In [61]:
np.vstack([d,e])

array([[1, 2],
       [3, 4],
       [2, 3],
       [4, 5]])

In [66]:
d = np.arange(1,13).reshape(3,4)
e = np.arange(1,5)
print(d)
print(e)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


In [68]:
np.vstack([d,e])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

# BroadCasting

In [71]:
d = np.arange(1,5)
e = np.arange(1,7)
print(d)
print(e)

[1 2 3 4]
[1 2 3 4 5 6]


In [73]:
d+2

array([3, 4, 5, 6])

In [76]:
np.broadcast(d,e)

ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [78]:
x = np.arange(1,7).reshape(3,2)
y = np.arange(1,3)
z = np.arange(1,4)
print(x)
print(y)
print(z)

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[1 2 3]


In [81]:
x*y

array([[ 1,  4],
       [ 3,  8],
       [ 5, 12]])

In [18]:
import numpy as np
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
mask = np.array([1, 0, 1, 0], dtype=bool)
print(row[:, None])
# print(X[row[:, np.newaxis], mask])

[[0]
 [1]
 [2]]


In [30]:
A = np.arange(1, 10).reshape(3,3,1)
B = np.arange(1, 10).reshape(3,3)

In [31]:
A = A.squeeze(axis=2) 
print(A)
B = np.expand_dims( B, axis=2)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [32]:
arr= np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [38]:

np.hstack((arr,arr[:,0])).shape = (3,3)
arr

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [39]:
a=np.array([[[ 0, 0, 0],
 [ 0, 0, 0],
 [ 0, 0, 0],
 [ 0, 0, 0]],
[[ 0, 0, 255],
 [255, 255, 255],
 [ 0, 0, 0],
 [255, 0, 0]]])
b = [255,0,255]
c = np.all(a==b,axis=1)
print(c) 

[[False  True False]
 [False False False]]


In [42]:
pad_matrix = np.array([[3, 2 ],
[1, 2],  
[3, 4],  
[5, 6]])
pad_matrix

array([[3, 2],
       [1, 2],
       [3, 4],
       [5, 6]])

In [48]:
np.pad(pad_matrix, 1)

array([[0, 0, 0, 0],
       [0, 3, 2, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 5, 6, 0],
       [0, 0, 0, 0]])

In [62]:
np.random.randint(4,9+1, size=(2,3))

array([[6, 6, 5],
       [9, 9, 7]])

In [54]:
np.random.uniform(9+1, size=(2,3))

array([[2.67438766, 1.87363613, 2.17263939],
       [1.03754883, 9.36635177, 2.48872095]])